// This file was auto-generated by tauri-ts-generator
// Do not edit this file manually

import { invoke } from "@tauri-apps/api/core";
import type { ModEntry } from "../types";

export async function greet(name: string): Promise<string> {
  return invoke<string>("greet", { name });
}

export async function updateLocalModlist(): Promise<void> {
  return invoke<void>("update_local_modlist");
}

export async function downloadMod(id: string): Promise<void> {
  return invoke<void>("download_mod", { id });
}

export async function getMods(): Promise<ModEntry[]> {
  return invoke<ModEntry[]>("get_mods");
}

export async function checkIfModInstalled(modId: string): Promise<boolean> {
  return invoke<boolean>("check_if_mod_installed", { modId });
}

export async function getNewestModVersion(modId: string): Promise<string> {
  return invoke<string>("get_newest_mod_version", { modId });
}

export async function triggerInstallMod(modId: string): Promise<boolean> {
  return invoke<boolean>("trigger_install_mod", { modId });
}

export async function triggerUninstallMod(modId: string): Promise<boolean> {
  return invoke<boolean>("trigger_uninstall_mod", { modId });
}

export async function getMod(modId: string): Promise<ModEntry> {
  return invoke<ModEntry>("get_mod", { modId });
}

export async function enableMod(modId: string): Promise<boolean> {
  return invoke<boolean>("enable_mod", { modId });
}

export async function disableMod(modId: string): Promise<boolean> {
  return invoke<boolean>("disable_mod", { modId });
}

export async function checkIfModEnabled(modId: string): Promise<boolean> {
  return invoke<boolean>("check_if_mod_enabled", { modId });
}

export async function checkIfModDisabled(modId: string): Promise<boolean> {
  return invoke<boolean>("check_if_mod_disabled", { modId });
}

export async function toggleMod(modId: string): Promise<void> {
  return invoke<void>("toggle_mod", { modId });
}

export async function launchGame(): Promise<void> {
  return invoke<void>("launch_game");
}

