// This file was auto-generated by tauri-ts-generator
// Do not edit this file manually

export interface ModEntry {
  id: string;
  titleSlug: string;
  displayTitle: string;
  authorSlug: string;
  displayAuthor: string;
  description: string;
  versions: Versions;
  configFiles: string[];
  dependencies: string[];
}

export type Versions = Record<string, string>;

